# Generated by Django 5.1 on 2024-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='body',
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='management',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='tips',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='weather',
            field=models.TextField(null=True),
        ),
    ]
