# Generated by Django 5.1 on 2024-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_plant_image_url_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(null=True, upload_to='media/plants/'),
        ),
    ]
